# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Random walk
#' @description  Random walk with Metropolis sampling method using Rcpp
#' @param sigma variance
#' @param x0 initial value
#' @param N sample size
#' @return a random sample of size N
#' @export
NULL

#' @title Laplace density
#' @description Laplace density
#' @param x real value
#' @return the density at x
#' @export
denLa <- function(x) {
    .Call('_StatComp20088_denLa', PACKAGE = 'StatComp20088', x)
}

RWcpp <- function(sigma, x0, N) {
    .Call('_StatComp20088_RWcpp', PACKAGE = 'StatComp20088', sigma, x0, N)
}

